### ISSUE TITLE
Slack models on GPU

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsModifiers.jl#115]
```julia
using Test, NLPModels, CUDA, NLPModelsModifiers, NLPModelsTest
nlp = LINSV(CuArray{Float64})
SlackModel(nlp) # fails
```
fails, because we expected NLPModelMeta{S, T} if nlp is of type AbstractNLPModel{S, T} (see https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/a9fa77496346fd5da171535295d949b570ac2f5a/src/slack-model.jl#L70 ).
However, nlp is {Float64, CuArray{Float64}} while the "slack" meta is {Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}
```
slackMeta = NLPModelsModifiers.slack_meta(meta) # https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/a9fa77496346fd5da171535295d949b570ac2f5a/src/slack-model.jl#L115
```

@amontoison an opinion on this? #114 is a suggestion to fix this.

**Comment by amontoison** [comment]
I suggest to use `S = eltype(v)` with `v` a vector allocated with `CuVector{Float64}(undef, n)` when we create the NLPModel.

**Comment by tmigot** [comment]
Not sure, I fully understand your suggestion. I guess my question is do you know the difference between `CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}` and `CuArray{Float64, 1}`? and is it a problem to cast `CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}` into `CuArray{Float64, 1}`?

**Comment by amontoison** [comment]
> Not sure, I fully understand your suggestion. My question is more do you know the difference between `CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}` and `CuArray{Float64, 1}`? and is it a problem to cast `CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}` into `CuArray{Float64, 1}`?

Yes, I know the difference.
The last attribute is the type of memory allocated by CUDA.
It can be host, device or unified memory.

I suggest this blog to understand it:
https://juliagpu.org/post/2023-11-07-cuda_5.1/
