### ISSUE TITLE
quasi-Newton approximation of Hessian of Lagrangian

### ISSUE THREAD

**Issue by MaxenceGollier** [JuliaSmoothOptimizers/NLPModelsModifiers.jl#129]
When we compute the Hessian of the Lagrangian in fact we compute the Hessian of the objective and the dual variables are discarded. 
I think this should not be the case, there is no reason for not approximating the constraints with a quasi-Newton model... 
IPOPT for example does compute each constraint as a quasi-Newton model when we use quasi-Newton approximations for the problem.

https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/c6befb7b5760f9c5db3a64308fe6994851c5e3c9/src/quasi-newton.jl#L188-L197

**Comment by tmigot** [comment]
Actually, @MaxenceGollier if you have a relatively small example with this it could be the start of a good tutorial?
