### ISSUE TITLE
No incrementation of `neval_hprod`

### ISSUE THREAD

**Issue by paraynaud** [JuliaSmoothOptimizers/NLPModelsModifiers.jl#86]
@dpo, I made some tests about TR-LBFGS.
The point was to check how many $Bv$ were done.
I was suprised to obtain `0` with `lbfgsnlp.model.counters.neval_hprod`.
I checked the code below, and there is no `increment!(qnnlp, :neval_hprod)` inside `hprod` nor `hprod!`.

https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/ca5bf2785e21a8e258ea31bafab6bc212781db26/src/quasi-newton.jl#L109
https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/ca5bf2785e21a8e258ea31bafab6bc212781db26/src/quasi-newton.jl#L120
https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/blob/ca5bf2785e21a8e258ea31bafab6bc212781db26/src/quasi-newton.jl#L127

However, I can retrieve the number of `mul!` done by the LBFGSOperator with `lbfgsnlp.op.nprod`.

Should I open a PR to add `increment!(qnnlp, :neval_hprod)` to `hprod` and `hprod!`?

**Comment by tmigot** [comment]
Good idea!

**Comment by dpo** [comment]
Yes I agree that it makes sense to count hprods for quasi-Newton models in the context of your research. Please open a PR.
