### ISSUE TITLE
Add counters to slack models

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsModifiers.jl#9]
For complete compatibility of all the NLPModels, shouldn't the `SlackModel` and the `SlackNLSModel` have a `counters` attribute? Typically, a JSO solver would use `nlp.counters` to verify limits on number of evaluations.

If you think that's useful, I can prepare a PR.

**Comment by dpo** [comment]
I think that would be useful, but they should redirect to counters of the underlying model.

**Comment by tmigot** [comment]
This is not needed, if we use the API to access evals.
